export const CONTACT_LIST = [
  {
    id: "2",
    isActive: true,
    isArchived: false,
    shortName: "HB",
    email: "henryboyd@gmail.com",
    name: "Henry Boyd",
    icon: "https://www.goodmorningimagesdownload.com/wp-content/uploads/2021/12/Free-Sunflower-Unique-Whatsapp-DP-Images-Pics-Download-1.jpg",
  },
  {
    id: "3",
    isArchived: false,
    number: 2,
    shortName: "MC",
    email: "marthacurtis@gmail.com",
    name: "Martha Curtis",
    icon: "https://www.goodmorningimagesdownload.com/wp-content/uploads/2021/12/Free-Sunflower-Unique-Whatsapp-DP-Images-Pics-Download-1.jpg",
  },
  {
    id: "4",
    isArchived: true,
    shortName: "RJ",
    email: "reidjerry@gmail.com",
    name: "Reid Jerry",
    icon: "https://www.goodmorningimagesdownload.com/wp-content/uploads/2021/12/Free-Sunflower-Unique-Whatsapp-DP-Images-Pics-Download-1.jpg",
  },
  {
    id: "5",
    isArchived: false,
    shortName: "CR",
    email: "christinereid@gmail.com",
    name: "Christine Reid",
    icon: "https://www.goodmorningimagesdownload.com/wp-content/uploads/2021/12/Free-Sunflower-Unique-Whatsapp-DP-Images-Pics-Download-1.jpg",
  },
  {
    id: "6",
    isArchived: true,
    shortName: "GP",
    email: "guzmphillis@gmail.com",
    name: "Guzm Phillis",
    icon: "https://www.goodmorningimagesdownload.com/wp-content/uploads/2021/12/Free-Sunflower-Unique-Whatsapp-DP-Images-Pics-Download-1.jpg",
  },
  {
    id: "7",
    isArchived: false,
    shortName: "JG",
    email: "jerryguzman@gmail.com",
    name: "Jerry Guzman",
    icon: "https://www.goodmorningimagesdownload.com/wp-content/uploads/2021/12/Free-Sunflower-Unique-Whatsapp-DP-Images-Pics-Download-1.jpg",
  },
  {
    id: "8",
    isArchived: false,
    shortName: "RW",
    email: "russellwilliams@gmail.com",
    name: "Russell Williams",
    icon: "https://www.goodmorningimagesdownload.com/wp-content/uploads/2021/12/Free-Sunflower-Unique-Whatsapp-DP-Images-Pics-Download-1.jpg",
  },
];
